export const ADD_BILL_ITEM = "ADD_BILL_ITEM"
export const EDIT_BILL_ITEM = "EDIT_BILL_ITEM"
export const REMOVE_BILL_ITEM = "REMOVE_BILL_ITEM"
export const UPDATE_BILL_CUSTOMER = "UPDATE_BILL_CUSTOMER"
