export const GET_CUSTOMERS = "GET_CUSTOMERS"
export const GET_PRODUCTS = "GET_PRODUCTS"
export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS"
export const GET_TRANSACTION_BY_TYPE = "GET_TRANSACTION_BY_TYPE"
